spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/station_alarm?serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000   # 1시간 (밀리초)

tago:
  api:
    key: ${TAGO_API_KEY}
    type: ${TAGO_API_TYPE:json}
    default-num-of-rows: ${TAGO_DEFAULT_NUM_OF_ROWS:10}

  station:
    base-url: ${TAGO_STATION_BASE_URL:http://apis.data.go.kr/1613000/BusSttnInfoInqireService}

  arrival:
    base-url: ${TAGO_ARRIVAL_BASE_URL:http://apis.data.go.kr/1613000/ArvlInfoInqireService}

alarm:
  batch:
    delay-ms: 60  # 알람 스케줄링 주기
    cooldown-seconds: 60 # Redis TTL 주기

firebase:
  credentials-path: ${FIREBASE_CREDENTIALS_PATH:serviceAccountKey.json}

server:
  port: 8080
